export enum OrderStatus {
  REVIEW = "EN REVISIÓN",
  PRE_APPROVED = "PRE-APROBADO",
  APPROVED = "APROBADO",
  DOCUMENT_PENDING = "DOCUMENTOS PENDIENTES",
  IN_PROGRESS = "EN CAMINO",
  DELIVERED = "ENTREGADO",
  DENIED = "DENEGADO",
}
