import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";

// import "@mantine/core/styles.layer.css";
import "mantine-datatable/styles.layer.css";
import "@mantine/dates/styles.css";
import React from "react";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { theme } from "../theme";
// import "style.css"
import "./styles.css";
import { RBACProvider } from "@/lib/contexts/RBACContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
        <ColorSchemeScript />
        {/* <script
          async
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
        /> */}
        <script src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js" defer></script>
        <script>
          window.OneSignalDeferred = window.OneSignalDeferred || [];
          OneSignalDeferred.push(async function(OneSignal) {
            await OneSignal.init({
              appId: "cc79af88-2135-4f63-a116-8587053ed0a9",
              allowLocalhostAsSecureOrigin: true,

            });
          });
        </script>
      </head>
      <body className="bg-background-light dark:bg-background-dark font-display text-text-light dark:text-text-dark">
        <MantineProvider
          // forceColorScheme="dark"
          theme={theme}
        >
          <RBACProvider>{children}</RBACProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
