import type { Metadata } from "next";
import "../globals.css";
import "@mantine/core/styles.css";

// import "@mantine/core/styles.layer.css";
import "mantine-datatable/styles.layer.css";
import "@mantine/dates/styles.css";
import React from "react";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { theme } from "../../theme";
// import "style.css"
import "../styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
        <ColorSchemeScript />
      </head>
      <body className="bg-gray-50 font-display text-gray-900">
        <MantineProvider
          forceColorScheme="light"
          theme={theme}
        >
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
